-- =====================================================================
--  ARQUIVO SUBSTITUÍDO — NÃO RODE.
--  A versão anterior deste script criava register_page_view/register_click
--  com visitor_id uuid; rodá-lo de novo recriaria uma função duplicada e
--  quebraria o rastreamento (erro PGRST203 / HTTP 300).
--  Tudo o que ele fazia agora está em supabase/003_fix_analytics.sql.
-- =====================================================================
